overblog_dataloader:
  defaults:
    promise_adapter: "overblog_dataloader.webonyx_graphql_sync_promise_adapter"
  loaders:
    flowers:
      alias: "flowers_dataloader"
      batch_load_fn: "App\\GraphQL\\Loader\\FlowerLoader::getFlowersPromise"
    shops:
      alias: "shops_dataloader"
      batch_load_fn: "@app.graph.shops_loader:getShopsPromise"