overblog_dataloader:
  defaults:
    promise_adapter: "overblog_dataloader.webonyx_graphql_sync_promise_adapter"
  loaders:
    flowers:
      alias: "flowers_dataloader"
      batch_load_fn: "@app.graph.flowers_loader:all"
