services:
  gedmo.listener.reference:
    class: Gedmo\References\ReferencesListener
    tags:
      - { name: doctrine_mongodb.odm.event_subscriber }
    calls:
      - [ setAnnotationReader, [ "@annotation_reader" ] ]
      - [ registerManager, [ 'entity', "@doctrine.orm.default_entity_manager" ] ]

  utils.listener.reference:
    class: App\Listener\ReferencesListener
    arguments: ["@service_container"]
    tags:
      - { name: doctrine.event_subscriber, connection: default }