security:
  providers:
    your_db_provider:
      entity:
        class: App\Entity\User
        property: apiToken
  firewalls:
    main:
      stateless: true
      anonymous: true
      lazy: true
      logout: ~
      guard:
        authenticators:
          - App\Security\ApiTokenAuthenticator