version: '3.8'

services:
  database:
    container_name: "${DATABASE_CONTAINER_NAME}"
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_USER: "${DATABASE_USER}"
      MYSQL_PASSWORD: "${DATABASE_PASS}"
    ports:
      - "${DATABASE_EXTERNAL_PORT}:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - app_net
  mongodb:
    container_name: "${MONGODB_CONTAINER_NAME}"
    image: mongo:4
    ports:
      - "${MONGODB_EXTERNAL_PORT}:27017"
    networks:
      app_net:
    volumes:
      - ./data/mongodb:/data/db
  php:
    container_name: "${PHP_CONTAINER_NAME}"
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    ports:
      - '9000:9000'
    volumes:
      - .:/app:delegated
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - database
      - mongodb
    networks:
      - app_net
  nginx:
    container_name: "${NGINX_CONTAINER_NAME}"
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - app_net
networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"