Flower:
  type: object
  config:
    description: "Flowers"
    fields:
      id:
        type: "Int!"
        description: "Flower id"
      name:
        type: "String!"
        description: "Flower name"
      flowerAttributes:
        type: "[FlowerAttribute]"
        description: "Flower attributes"
        access: "@=isAuthenticated()"
      shops:
        type: "[Shop]"
        description: "Shops that have these flowers"
