FlowerAttribute:
  type: object
  config:
    description: "Flower attribute"
    fields:
      id:
        type: "Int!"
        description: "Attribute id"
      attributeName:
        type: "String!"
        description: "Attribute name"
      value:
        type: "String!"
        description: "Attribute value"
