Purchase:
  type: object
  config:
    description: "Purchases"
    fields:
      id:
        type: "String!"
        description: "Purchase id"
      customerName:
        type: "String!"
        description: "Customer name"
