Shop:
  type: object
  config:
    description: "Flower shop"
    fields:
      id:
        type: "Int!"
        description: "Flower shop id"
      name:
        type: "String!"
        description: "Flower shop name"
      address:
        type: "String"
        description: "Flower shop address"
      flowers:
        type: "[Flower]"
        description: "The flowers of this shop"
        args:
          attributeValue:
            type: "String"
            description: "Flower attributes"
        resolve: '@=resolver("App\\GraphQL\\Resolver\\FlowerResolver::resolveByAttributeAndShop", [value, args])'
      purchases:
        type: "[Purchase]"
        description: "Purchases made in the shop"
