FlowerInput:
  type: input-object
  config:
    fields:
      name:
        type: "String!"
        description: "Имя создаваемого цветка"
        validation:
          - Length:
              min: 6
              max: 32
      flowerAttributes:
        type: "[FlowerAttributeInput]"
        description: "Совйства цветка"
