FlowerInput:
  type: input-object
  config:
    fields:
      name:
        type: "String!"
        description: "Имя создаваемого цветка"
      flowerAttributes:
        type: "[FlowerAttributeInput]"
        description: "Совйства цветка"
