FlowerAttributeInput:
  type: input-object
  config:
    description: "Flower attribute"
    fields:
      attributeName:
        type: "String!"
        description: "Attribute name"
      value:
        type: "String!"
        description: "Attribute value"
