FlowerInput:
  type: input-object
  config:
    fields:
      name:
        type: "String!"
        description: "Flower name"
        validation:
          - Length:
              min: 6
              max: 32
      flowerAttributes:
        type: "[FlowerAttributeInput]"
        description: "Flower attribute"
