ShopInput:
  type: input-object
  config:
    description: "Adding a shop"
    fields:
      name:
        type: "String!"
        description: "Shop name"
        validation:
          link: App\Entity\Shop::$name
      address:
        type: "String"
        description: "Shop address"
      flowers:
        type: "[FlowerInput]"
        description: "The flowers of this shop"
      purchases:
        type: "[PurchaseInput]"
        description: "Purchases made in the shop"
