Mutation:
  type: object
  config:
    fields:
      createFlower:
        type: "Flower"
        resolve: "@=mutation('create_flower', [args])"
        args:
          input:
            type: "FlowerInput"
      createShop:
        type: "Shop"
        resolve: "@=mutation('create_shop', [args])"
        args:
          input:
            type: "ShopInput"