Query:
  type: object
  config:
    description: "Main query"
    fields:
      flower:
        type: "Flower"
        args:
          id:
            type: "Int!"
            description: "Идентификатор цветка"
        resolve: '@=resolver("App\\GraphQL\\Resolver\\FlowerResolver::resolve", [args["id"]])'
      flowers:
        type: "[Flower]"
        args:
          limit:
            type: "Int"
            description: "Количество цветов"
        resolve: '@=resolver("App\\GraphQL\\Resolver\\FlowerCollectionResolver::resolve", [args["limit"]])'
      shop:
        type: "Shop"
        args:
          id:
            type: "Int!"
            description: "Идентификатор магазина"
        resolve: '@=resolver("App\\GraphQL\\Resolver\\ShopResolver::resolve", [args["id"], context])'
      shops:
        type: "[Shop]"
        args:
          limit:
            type: "Int"
            description: "Количество магазинов"
        resolve: '@=resolver("App\\GraphQL\\Resolver\\ShopCollectionResolver::resolve", [args["limit"]])'
      flowerAttributes:
        type: "[FlowerAttribute]"
        args:
          flower_id:
            type: "Int!"
            description: "Идентификатор цветка"
        resolve: '@=resolver("App\\GraphQL\\Resolver\\FlowerAttributeResolver::resolve", [args["flower_id"]])'
