Flower:
  type: object
  config:
    description: "Различные цветочки"
    fields:
      id:
        type: "Int!"
        description: "Идентификатор цветка"
      name:
        type: "String!"
        description: "Название цветка"
        access: "@=isAuthenticated()"
      flowerAttributes:
        type: "[FlowerAttribute]"
        description: "Совйства цветка"
      shops:
        type: "[Shop]"
        description: "Магазины в которых есть эти цветы"
