FlowerAttribute:
  type: object
  config:
    description: "Свойство цветка"
    fields:
      id:
        type: "Int!"
        description: "Идентификатор свойства"
      attributeName:
        type: "String!"
        description: "Название свойства"
      value:
        type: "String!"
        description: "Значение свойства"
