Shop:
  type: object
  config:
    description: "Цветочные магазины"
    fields:
      id:
        type: "Int!"
        description: "Идентификатор цветочного магазина"
      name:
        type: "String!"
        description: "Название цветочного магазина"
      address:
        type: "String"
        description: "Адрес цветочного магазина"
      flowers:
        type: "[Flower]"
        description: "Цветы в этом магазине"
      purchases:
        type: "[Purchase]"
        description: "Покупки совершенные в этом магазине"
